### PR TITLE
Added companion object definitions for case classes

### PR DESCRIPTION
**Pull request by stevevickers**
This version adds two cats implicits.  Generating monocle lenses
is planned next.

### CODE REVIEW

**Comment by adrobisch** [comment]
:+1:, as a general comment: I think it would be great to have toggles/params for everything that generates references to types outside the standard lib. See https://github.com/commercetools/scraml/blob/main/src/main/scala/scraml/ModelGen.scala#L15
for example.

**Comment by stevevickers** [comment]
> 👍, as a general comment: I think it would be great to have toggles/params for everything that generates references to types outside the standard lib. See https://github.com/commercetools/scraml/blob/main/src/main/scala/scraml/ModelGen.scala#L15
> for example.

I totally agree.  This version does not have it (yet) but could have one for each of:

- cats
- monocle
- circe

Also, what do you think about augmenting `ModelGenParams` with the supported toggles?

**Comment by adrobisch** [comment]
@stevevickers I incorporated the cats features with basic JSON derivation support. Will merge this now to unblock https://github.com/commercetools/sphere-backend/pull/7460. Feel free to come up with another PR if there are things you don't like in the last commits.

**Comment by stevevickers** [comment]
> Feel free to come up with another PR if there are things you don't like in the last commits.

I have no problem with your commits, good sir 😄 .

If you don't mind too much, I will have another PR soon which refactors third-party library support code generation into an `abstract class Decorator` and `object Decorators` types (enabled by feature flags such as what you did with `params.catsSupport`) to allow for additional generated integration with desired components as determined by `sbt` `settingKey`s.

**Comment by adrobisch** [comment]
@stevevickers :+1: the `DefaultModelGen` was getting messy, I refactored it a bit while adding one more Sphere JSON aspect: https://github.com/commercetools/scraml/commit/d95d59d3506f22b026857048e51f0d211bf3e568 might be in the same direction as your `Decorator` approach.

**Pull request merged**
