### PR TITLE
(build): update docs after publish

### PR DESCRIPTION
**Pull request by adrobisch**
this adds `ghpagesPushSite` to the release step
+ upgrade sbt-paradox (was throwing errors on `makeSite` with Java 17)

not :100: this works out with the matrix and the github token as it, but since there is only one Scala/Java defined and GITHUB_TOKEN is in `env`, I think it could work like that

### CODE REVIEW

**Comment by osxhacker** [comment]
On a related note, updating `sbt-paradox` to `v0.10.3` appears to have eliminated the need to explicitly "unlock" packages for reflection.  This was required for successful `sbt-paradox` execution using `v0.9.2` and JDK 17+ thusly:

```
JAVA_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED" sbt paradox
```

See [here](https://dev.java/learn/circumventing-strong-encapsulation-with---add-exports-and---add-opens/) for details.

👍

**Comment by osxhacker** [comment]
FWIW, the current `ci.yml` definition updates the [docs](https://commercetools.github.io/scraml/) whenever a build is initiated.  This causes the displayed `version` to be a "pre-tagged" version, such as `0.13.1+0-ea2eae21+20221210-1443`.

I'm not sure if the Github Actions `needs: [build]` property can be made conditional or not.  Perhaps an `on:` section introduced into the `publish:` job could achieve this?  (I don't know if that is supported BTW)

If the above is not easy to specify, then it's a small discrepancy and not a blocker IMHO.

**Comment by adrobisch** [comment]
Modifying `githubWorkflowPublish` should only affect the `publish` job which is only [executed on tags](https://github.com/commercetools/scraml/blob/1e25805ffd47154973376a53bf3b9874f90b441b/.github/workflows/ci.yml#L71), so I think your points are already addressed.  There is no way to configure permissions right now (but https://github.com/sbt/sbt-github-actions/pull/105 looks promising). Will look into working around that or maybe just wait for that to be merged.

**Comment by osxhacker** [comment]
> Modifying `githubWorkflowPublish` should only affect the `publish` job which is only [executed on tags](https://github.com/commercetools/scraml/blob/1e25805ffd47154973376a53bf3b9874f90b441b/.github/workflows/ci.yml#L71), so I think your points are already addressed. There is no way to configure permissions right now (but [sbt/sbt-github-actions#105](https://github.com/sbt/sbt-github-actions/pull/105) looks promising). Will look into working around that or maybe just wait for that to be merged.

Alles gut, alles klar 👍 .

**Comment by osxhacker** [comment]
@adrobisch ,

This PR has had no activity for quite some time and, since it is an edge case regarding a minor documentation generation detail, perhaps it could be closed?

**Pull request merged**
